name: Thunder-5.2-HelloPlugin-test

on:
  push:
    branches: [ main, develop, 'support/**', 'hotfix/**', 'topic/**']
  pull_request:
    branches: [ main, develop, 'support/**', 'hotfix/**', 'topic/**']
  workflow_dispatch:   # manual trigger

env:
  THUNDER_REF: "R5.2.0"

jobs:
  HelloPlugin-test:
    name: Build and run unit tests
    runs-on: ubuntu-22.04

    steps:
      # Set up Thunder cache
      - name: Set up Thunder cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            build/Thunder
            build/ThunderTools
            install
            !install/etc/thunder/plugins
            !install/usr/lib/thunder/plugins
          key: thunder-${{ env.THUNDER_REF }}-rdk

      - name: Install packages
        run: |
          sudo apt update
          sudo apt-get install -y pkg-config libglib2.0-dev libnm-dev libcurl4-openssl-dev lcov ninja-build libgupnp-1.2-1 libgupnp-1.2-dev libgssdp-1.2-0 libsoup2.4-1

      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install jsonref

      - name: Configure CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'

      - name: Checkout thunder repositories
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/rdkcentral/ThunderTools ThunderTools --branch ${{ env.THUNDER_REF }}
          git clone https://github.com/rdkcentral/Thunder Thunder --branch ${{ env.THUNDER_REF }}

      - name: Checkout HelloPLugin
        uses: actions/checkout@v3
        with:
          path: HelloPlugin

      - name: Build ThunderTools
        if: steps.cache.outputs.cache-hit != 'true'
        run: >
          cmake
          -S "${{github.workspace}}/ThunderTools" -B build/ThunderTools
          -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install/usr"
          -DCMAKE_MODULE_PATH="${{github.workspace}}/install/tools/cmake"
          -DGENERIC_CMAKE_MODULE_PATH="${{github.workspace}}/install/tools/cmake"
          &&
          cmake --build build/ThunderTools --target install -j8

      - name: Build Thunder
        if: steps.cache.outputs.cache-hit != 'true'
        run: >
          cmake
          -S "${{github.workspace}}/Thunder" -B build/Thunder
          -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install/usr"
          -DCMAKE_MODULE_PATH="${{github.workspace}}/install/tools/cmake"
          -DBUILD_TYPE=Debug
          -DBINDING=127.0.0.1
          -DPORT=9998
          -DTRACING=OFF
          -DMESSAGING=ON
          -DENABLED_TRACING_LEVEL=2
          &&
          cmake --build build/Thunder --target install -j8

      - name: Build HelloPlugin
        run: >
          cmake
          -S "${{github.workspace}}/HelloPlugin"
          -B build/HelloPlugin
          -DCMAKE_TOOLCHAIN_FILE="${{ env.TOOLCHAIN_FILE }}"
          -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install/usr"
          -DCMAKE_MODULE_PATH="${{github.workspace}}/install/tools/cmake"
          &&
          cmake --build build/HelloPlugin --target install -j8
